# Generated by Django 2.1.1 on 2018-09-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='website',
        ),
        migrations.AddField(
            model_name='user',
            name='employee_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
