# Generated by Django 2.1.1 on 2018-09-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180918_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first',
            field=models.CharField(blank=True, max_length=110),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
