# Generated by Django 2.1.1 on 2018-09-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_employeeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='pay',
            field=models.IntegerField(default=11),
        ),
    ]
