# Generated by Django 2.1.1 on 2018-09-22 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20180921_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('quantity', models.FloatField(default=0)),
                ('unit', models.CharField(choices=[('FLOZ', 'fl-oz'), ('WTOZ', 'wt-oz'), ('EA', 'each'), ('GAL', 'gal'), ('PT', 'pint'), ('QT', 'quart')], default='fl-oz', max_length=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.InventoryProfile')),
            ],
            options={
                'verbose_name_plural': 'Recipe Items',
            },
        ),
        migrations.RemoveField(
            model_name='recipeprofile',
            name='build',
        ),
        migrations.RemoveField(
            model_name='recipeprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recipeprofile',
            name='unit',
        ),
    ]
