# Generated by Django 2.1.1 on 2018-09-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20180921_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeitems',
            old_name='quantity',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='recipeitems',
            name='item_name',
        ),
        migrations.AddField(
            model_name='recipeitems',
            name='category',
            field=models.CharField(choices=[('RAW', 'raw'), ('PREP', 'prep'), ('SPICE', 'spice'), ('APPS', 'apps'), ('ENTREE', 'entree')], default='prep', max_length=15),
        ),
        migrations.AddField(
            model_name='recipeitems',
            name='serving_size',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipeitems',
            name='yeild',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='recipeitems',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
