# Generated by Django 2.1.1 on 2018-09-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20180922_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeitems',
            name='sku',
            field=models.FloatField(default=0),
        ),
    ]
