# Generated by Django 2.1.1 on 2018-09-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_recipeitems_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeitems',
            name='case',
            field=models.FloatField(default=0),
        ),
    ]
