# Generated by Django 2.1.1 on 2018-09-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_recipeitems_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeitems',
            name='description',
            field=models.CharField(default='stuff', max_length=50),
            preserve_default=False,
        ),
    ]
