# Generated by Django 2.1.1 on 2018-09-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20180922_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeitems',
            name='company',
            field=models.CharField(default='packer', max_length=50),
            preserve_default=False,
        ),
    ]
