# Generated by Django 2.1.1 on 2018-09-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20180922_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCountProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('steak', models.FloatField(default=0)),
                ('sirloin', models.FloatField(default=0)),
                ('beef_patty', models.FloatField(default=0)),
                ('chicken_wing', models.FloatField(default=0)),
                ('chicken_breast', models.FloatField(default=0)),
                ('hotdog', models.FloatField(default=0)),
                ('bacon', models.FloatField(default=0)),
                ('salt', models.FloatField(default=0)),
                ('pepper_black', models.FloatField(default=0)),
                ('pepper_red_flakes', models.FloatField(default=0)),
                ('sugar', models.FloatField(default=0)),
                ('sugar_brown', models.FloatField(default=0)),
                ('garlic_granulated', models.FloatField(default=0)),
                ('garlic_powder', models.FloatField(default=0)),
                ('onion_powder', models.FloatField(default=0)),
                ('parsley_dry', models.FloatField(default=0)),
                ('cinnamon_ground', models.FloatField(default=0)),
                ('bay_leaves', models.FloatField(default=0)),
                ('italian_seasoning', models.FloatField(default=0)),
                ('sriracha', models.FloatField(default=0)),
                ('ketchup_20oz', models.FloatField(default=0)),
                ('ketchup_10c', models.FloatField(default=0)),
                ('mustard', models.FloatField(default=0)),
                ('oil_truffle', models.FloatField(default=0)),
                ('oil_90_10', models.FloatField(default=0)),
                ('oil_shortening', models.FloatField(default=0)),
                ('honey', models.FloatField(default=0)),
                ('tahini', models.FloatField(default=0)),
                ('lemon_juice', models.FloatField(default=0)),
                ('mango_nectar', models.FloatField(default=0)),
                ('lemonade_mix', models.FloatField(default=0)),
                ('chili_sauce', models.FloatField(default=0)),
                ('a1_sauce', models.FloatField(default=0)),
                ('vinegar_malt', models.FloatField(default=0)),
                ('cocao_hershey', models.FloatField(default=0)),
                ('cherries_marashino', models.FloatField(default=0)),
                ('banana_pepper_hot', models.FloatField(default=0)),
                ('bbq_sw_sp', models.FloatField(default=0)),
                ('gojujang_sc', models.FloatField(default=0)),
                ('pineapple_juice', models.FloatField(default=0)),
                ('beans_garbanzo', models.FloatField(default=0)),
                ('beans_red_kidney', models.FloatField(default=0)),
                ('tomato_can_peeled', models.FloatField(default=0)),
                ('tomato_can_whole', models.FloatField(default=0)),
                ('sauce_cheddar', models.FloatField(default=0)),
                ('broth_beef', models.FloatField(default=0)),
                ('broth_chicken', models.FloatField(default=0)),
                ('jalapeno_slice', models.FloatField(default=0)),
                ('pepperoncini', models.FloatField(default=0)),
                ('mayonnaise', models.FloatField(default=0)),
                ('russian_dressing', models.FloatField(default=0)),
                ('marinara_salsa', models.FloatField(default=0)),
                ('chipotle_in_adobo', models.FloatField(default=0)),
                ('giardiniara', models.FloatField(default=0)),
                ('potato_chips', models.FloatField(default=0)),
                ('molasses_fancy', models.FloatField(default=0)),
                ('hot_sauce_franks', models.FloatField(default=0)),
                ('el_yucateco', models.FloatField(default=0)),
                ('vinegar_apple_cider', models.FloatField(default=0)),
                ('whip_cream', models.FloatField(default=0)),
                ('creamer', models.FloatField(default=0)),
                ('pita_bread', models.FloatField(default=0)),
                ('olives', models.FloatField(default=0)),
                ('eggs', models.FloatField(default=0)),
                ('sub_panini_roll', models.FloatField(default=0)),
                ('hamberger_bun', models.FloatField(default=0)),
                ('brioche_bun_4', models.FloatField(default=0)),
                ('brioche_bun_2', models.FloatField(default=0)),
                ('oranges', models.FloatField(default=0)),
                ('limes', models.FloatField(default=0)),
                ('potato', models.FloatField(default=0)),
                ('brussels_sprouts', models.FloatField(default=0)),
                ('tomato', models.FloatField(default=0)),
                ('romaine_lettuce', models.FloatField(default=0)),
                ('red_onion', models.FloatField(default=0)),
                ('white_onion', models.FloatField(default=0)),
                ('pickles', models.FloatField(default=0)),
                ('avocado', models.FloatField(default=0)),
                ('cucumber', models.FloatField(default=0)),
                ('red_pepper', models.FloatField(default=0)),
                ('yellow_pepper', models.FloatField(default=0)),
                ('garlic', models.FloatField(default=0)),
                ('leeks', models.FloatField(default=0)),
                ('scallions', models.FloatField(default=0)),
                ('basil', models.FloatField(default=0)),
                ('jalapeno_fresh', models.FloatField(default=0)),
                ('cilantro', models.FloatField(default=0)),
                ('cheese_romano', models.FloatField(default=0)),
                ('cheese_swiss', models.FloatField(default=0)),
                ('cheese_provalone', models.FloatField(default=0)),
                ('cheese_cheddar', models.FloatField(default=0)),
                ('cheese_pepperjack', models.FloatField(default=0)),
                ('cheese_parmesan', models.FloatField(default=0)),
                ('butter', models.FloatField(default=0)),
                ('buttermilk', models.FloatField(default=0)),
                ('heavy_cream', models.FloatField(default=0)),
                ('sour_cream', models.FloatField(default=0)),
                ('fries', models.FloatField(default=0)),
                ('fries_sweet_potato', models.FloatField(default=0)),
                ('broccoli_bites', models.FloatField(default=0)),
                ('jalapeno_poppers', models.FloatField(default=0)),
                ('mozzerella_sticks', models.FloatField(default=0)),
                ('hash_brown_patty', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='RecipeItems',
        ),
        migrations.DeleteModel(
            name='RecipeProfile',
        ),
        migrations.AlterModelOptions(
            name='inventoryprofile',
            options={'verbose_name_plural': 'Inventory'},
        ),
        migrations.RenameField(
            model_name='inventoryprofile',
            old_name='a1_sauce',
            new_name='case',
        ),
        migrations.RenameField(
            model_name='inventoryprofile',
            old_name='avocado',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='inventoryprofile',
            old_name='bacon',
            new_name='serving_size',
        ),
        migrations.RenameField(
            model_name='inventoryprofile',
            old_name='banana_pepper_hot',
            new_name='yeild',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='basil',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='bay_leaves',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='bbq_sw_sp',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='beans_garbanzo',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='beans_red_kidney',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='beef_patty',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='brioche_bun_2',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='brioche_bun_4',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='broccoli_bites',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='broth_beef',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='broth_chicken',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='brussels_sprouts',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='butter',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='buttermilk',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='cheese_cheddar',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='cheese_parmesan',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='cheese_pepperjack',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='cheese_provalone',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='cheese_romano',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='cheese_swiss',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='cherries_marashino',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='chicken_breast',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='chicken_wing',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='chili_sauce',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='chipotle_in_adobo',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='cilantro',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='cinnamon_ground',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='cocao_hershey',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='creamer',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='cucumber',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='eggs',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='el_yucateco',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='fries',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='fries_sweet_potato',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='garlic',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='garlic_granulated',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='garlic_powder',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='giardiniara',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='gojujang_sc',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='hamberger_bun',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='hash_brown_patty',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='heavy_cream',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='honey',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='hot_sauce_franks',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='hotdog',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='italian_seasoning',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='jalapeno_fresh',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='jalapeno_poppers',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='jalapeno_slice',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='ketchup_10c',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='ketchup_20oz',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='leeks',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='lemon_juice',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='lemonade_mix',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='limes',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='mango_nectar',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='marinara_salsa',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='mayonnaise',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='molasses_fancy',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='mozzerella_sticks',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='mustard',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='oil_90_10',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='oil_shortening',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='oil_truffle',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='olives',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='onion_powder',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='oranges',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='parsley_dry',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='pepper_black',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='pepper_red_flakes',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='pepperoncini',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='pickles',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='pineapple_juice',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='pita_bread',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='potato',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='potato_chips',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='red_onion',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='red_pepper',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='romaine_lettuce',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='russian_dressing',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='sauce_cheddar',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='scallions',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='sirloin',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='sour_cream',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='sriracha',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='steak',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='sub_panini_roll',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='sugar',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='sugar_brown',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='tahini',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='tomato',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='tomato_can_peeled',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='tomato_can_whole',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='vinegar_apple_cider',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='vinegar_malt',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='whip_cream',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='white_onion',
        ),
        migrations.RemoveField(
            model_name='inventoryprofile',
            name='yellow_pepper',
        ),
        migrations.AddField(
            model_name='inventoryprofile',
            name='category',
            field=models.CharField(choices=[('RAW', 'raw'), ('FRESH', 'fresh'), ('DAIRY', 'dairy'), ('PREP', 'prep'), ('SPICE', 'spice'), ('APPS', 'apps'), ('ENTREE', 'entree')], default='prep', max_length=15),
        ),
        migrations.AddField(
            model_name='inventoryprofile',
            name='company',
            field=models.CharField(default='c', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryprofile',
            name='sku',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryprofile',
            name='unit',
            field=models.CharField(choices=[('FLOZ', 'fl-oz'), ('WTOZ', 'wt-oz'), ('EA', 'each'), ('GAL', 'gal'), ('PT', 'pint'), ('QT', 'quart')], default='fl-oz', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventoryprofile',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
