# Generated by Django 2.1.1 on 2018-09-22 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20180922_0210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryprofile',
            old_name='yeild',
            new_name='serving_yield',
        ),
    ]
