# Generated by Django 2.1.1 on 2018-09-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20180922_0331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditEmployeeProfile',
        ),
        migrations.AlterModelOptions(
            name='inventorycountprofile',
            options={'verbose_name_plural': 'Inventory Count'},
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='active',
            field=models.CharField(choices=[('active', 'Active'), ('not active', 'Not Active')], default='active', max_length=15),
            preserve_default=False,
        ),
    ]
