# Generated by Django 2.1.1 on 2018-09-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20180923_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=50)),
                ('monday', models.FloatField(default=0)),
                ('tuesday', models.FloatField(default=0)),
                ('wednesday', models.FloatField(default=0)),
                ('thursday', models.FloatField(default=0)),
                ('friday', models.FloatField(default=0)),
                ('saturday', models.FloatField(default=0)),
                ('sunday', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('period', models.FloatField(default=0)),
            ],
        ),
    ]
