# Generated by Django 2.1.1 on 2018-09-24 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_salesprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesProfile',
        ),
    ]
