# Generated by Django 2.1.1 on 2018-10-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20180925_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
