# Generated by Django 2.2.2 on 2019-06-12 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_inventorysequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTotals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='salestotals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_total', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ActualSalesProfile')),
                ('forcast_total', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ForcastedSalesProfile')),
            ],
        ),
    ]
